// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaIWB6J-SX24-Qr7fSA0enneRSsVGA768',
    appId: '1:861949666513:web:0ddd7a3ec3c107ae4391f0',
    messagingSenderId: '861949666513',
    projectId: 'fashion-app-project-aa763',
    authDomain: 'fashion-app-project-aa763.firebaseapp.com',
    storageBucket: 'fashion-app-project-aa763.firebasestorage.app',
    measurementId: 'G-1WYB5RJR87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5WJkO9fvk_9OdRg7PclL7CEqTuTexzGY',
    appId: '1:861949666513:android:138f510b73943f434391f0',
    messagingSenderId: '861949666513',
    projectId: 'fashion-app-project-aa763',
    storageBucket: 'fashion-app-project-aa763.firebasestorage.app',
  );
}
